plugins: [
  jekyll-include-cache
]
remote_theme: "mmistakes/minimal-mistakes@4.16.4"
minimal_mistakes_skin: "dirt"

# Site Settings
locale                   : "en-US"
title                    : "个人笔记"
title_separator          : "-"
name                     : "Lgun"
description              : "An amazing website."
url                      : "https://hejy47.github.io"
baseurl                  : "/Notes"
repository               : "hejy47/Notes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/Images/icon.jpg"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title

